create extension if not exists pgcrypto;

create table if not exists public.all_star_markets (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  season integer not null,
  postseason boolean not null default false,
  category text not null check (category in ('asg_winner', 'asg_mvp', 'contest_winner')),
  title text not null,
  subtitle text,
  event_date date not null,
  lock_at timestamptz not null,
  status text not null default 'open' check (status in ('open', 'locked', 'resolved')),
  multiplier integer not null check (multiplier between 1 and 5),
  winning_option_id bigint,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.all_star_market_options (
  id bigint generated by default as identity primary key,
  market_id bigint not null references public.all_star_markets(id) on delete cascade,
  label text not null,
  subtitle text,
  option_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (market_id, label),
  unique (id, market_id)
);

create table if not exists public.all_star_picks (
  id uuid primary key default gen_random_uuid(),
  market_id bigint not null references public.all_star_markets(id) on delete cascade,
  option_id bigint not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  confidence_score integer not null check (confidence_score between 1 and 3),
  correct boolean,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint all_star_picks_option_matches_market_fkey
    foreign key (option_id, market_id)
    references public.all_star_market_options(id, market_id)
    on delete cascade,
  unique (market_id, user_id)
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'all_star_markets_winning_option_id_fkey'
      and conrelid = 'public.all_star_markets'::regclass
  ) then
    alter table public.all_star_markets
    add constraint all_star_markets_winning_option_id_fkey
    foreign key (winning_option_id)
    references public.all_star_market_options(id)
    on delete set null;
  end if;
end
$$;

create index if not exists idx_all_star_markets_date_season
  on public.all_star_markets (event_date, season, postseason);

create index if not exists idx_all_star_options_market
  on public.all_star_market_options (market_id, option_order);

create index if not exists idx_all_star_picks_market
  on public.all_star_picks (market_id, user_id);

create index if not exists idx_all_star_picks_correct
  on public.all_star_picks (correct);

create or replace function public.set_all_star_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_all_star_markets_updated_at on public.all_star_markets;
create trigger trg_all_star_markets_updated_at
before update on public.all_star_markets
for each row execute function public.set_all_star_updated_at();

drop trigger if exists trg_all_star_options_updated_at on public.all_star_market_options;
create trigger trg_all_star_options_updated_at
before update on public.all_star_market_options
for each row execute function public.set_all_star_updated_at();

drop trigger if exists trg_all_star_picks_updated_at on public.all_star_picks;
create trigger trg_all_star_picks_updated_at
before update on public.all_star_picks
for each row execute function public.set_all_star_updated_at();

alter table public.all_star_markets enable row level security;
alter table public.all_star_market_options enable row level security;
alter table public.all_star_picks enable row level security;

drop policy if exists "all_star_markets_select" on public.all_star_markets;
create policy "all_star_markets_select"
on public.all_star_markets
for select
using (true);

drop policy if exists "all_star_market_options_select" on public.all_star_market_options;
create policy "all_star_market_options_select"
on public.all_star_market_options
for select
using (true);

drop policy if exists "all_star_picks_select" on public.all_star_picks;
create policy "all_star_picks_select"
on public.all_star_picks
for select
using (true);

drop policy if exists "all_star_picks_insert_own" on public.all_star_picks;
create policy "all_star_picks_insert_own"
on public.all_star_picks
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "all_star_picks_update_own" on public.all_star_picks;
create policy "all_star_picks_update_own"
on public.all_star_picks
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "all_star_picks_delete_own" on public.all_star_picks;
create policy "all_star_picks_delete_own"
on public.all_star_picks
for delete
to authenticated
using (auth.uid() = user_id);

insert into public.all_star_markets (
  slug,
  season,
  postseason,
  category,
  title,
  subtitle,
  event_date,
  lock_at,
  status,
  multiplier,
  sort_order
)
values
  (
    '2026-shooting-stars-winner',
    2025,
    false,
    'contest_winner',
    'Shooting Stars Winner',
    'NBA All-Star Saturday Night',
    '2026-02-14',
    '2026-02-14 20:00:00-08',
    'open',
    3,
    10
  ),
  (
    '2026-3pt-contest-winner',
    2025,
    false,
    'contest_winner',
    '3-Point Contest Winner',
    'NBA All-Star Saturday Night',
    '2026-02-14',
    '2026-02-14 20:30:00-08',
    'open',
    3,
    20
  ),
  (
    '2026-slam-dunk-winner',
    2025,
    false,
    'contest_winner',
    'Slam Dunk Winner',
    'NBA All-Star Saturday Night',
    '2026-02-14',
    '2026-02-14 21:10:00-08',
    'open',
    3,
    30
  ),
  (
    '2026-asg-winner',
    2025,
    false,
    'asg_winner',
    'All-Star Game Winner',
    'NBA All-Star Game',
    '2026-02-15',
    '2026-02-15 17:00:00-08',
    'open',
    2,
    40
  ),
  (
    '2026-asg-mvp',
    2025,
    false,
    'asg_mvp',
    'All-Star Game MVP',
    'Pick the player who wins 2026 Kobe Bryant MVP',
    '2026-02-15',
    '2026-02-15 17:00:00-08',
    'open',
    3,
    50
  )
on conflict (slug) do update
set
  title = excluded.title,
  subtitle = excluded.subtitle,
  event_date = excluded.event_date,
  lock_at = excluded.lock_at,
  status = excluded.status,
  multiplier = excluded.multiplier,
  sort_order = excluded.sort_order,
  updated_at = now();

with shooting_stars_market as (
  select id from public.all_star_markets where slug = '2026-shooting-stars-winner'
)
insert into public.all_star_market_options (market_id, label, subtitle, option_order)
select
  shooting_stars_market.id,
  option_rows.label,
  option_rows.subtitle,
  option_rows.option_order
from shooting_stars_market
cross join (
  values
    ('Team All-Star', 'Shooting Stars participant team', 1),
    ('Team Cavalry', 'Shooting Stars participant team', 2),
    ('Team Grind', 'Shooting Stars participant team', 3),
    ('Team Rooks', 'Shooting Stars participant team', 4)
) as option_rows(label, subtitle, option_order)
on conflict (market_id, label) do update
set subtitle = excluded.subtitle,
    option_order = excluded.option_order,
    updated_at = now();

with contest_market as (
  select id from public.all_star_markets where slug = '2026-3pt-contest-winner'
)
insert into public.all_star_market_options (market_id, label, subtitle, option_order)
select
  contest_market.id,
  option_rows.label,
  option_rows.subtitle,
  option_rows.option_order
from contest_market
cross join (
  values
    ('Darius Garland', '3-Point Contest', 1),
    ('Tyler Herro', '3-Point Contest', 2),
    ('Buddy Hield', '3-Point Contest', 3),
    ('Cam Johnson', '3-Point Contest', 4),
    ('Norman Powell', '3-Point Contest', 5),
    ('Payton Pritchard', '3-Point Contest', 6),
    ('Anfernee Simons', '3-Point Contest', 7),
    ('Victor Wembanyama', '3-Point Contest', 8)
) as option_rows(label, subtitle, option_order)
on conflict (market_id, label) do update
set subtitle = excluded.subtitle,
    option_order = excluded.option_order,
    updated_at = now();

with dunk_market as (
  select id from public.all_star_markets where slug = '2026-slam-dunk-winner'
)
insert into public.all_star_market_options (market_id, label, subtitle, option_order)
select
  dunk_market.id,
  option_rows.label,
  option_rows.subtitle,
  option_rows.option_order
from dunk_market
cross join (
  values
    ('Andre Jackson Jr.', 'Slam Dunk Contest', 1),
    ('Stephon Castle', 'Slam Dunk Contest', 2),
    ('Matas Buzelis', 'Slam Dunk Contest', 3),
    ('Dalon Knecht', 'Slam Dunk Contest', 4)
) as option_rows(label, subtitle, option_order)
on conflict (market_id, label) do update
set subtitle = excluded.subtitle,
    option_order = excluded.option_order,
    updated_at = now();

with winner_market as (
  select id from public.all_star_markets where slug = '2026-asg-winner'
)
insert into public.all_star_market_options (market_id, label, subtitle, option_order)
select
  winner_market.id,
  option_rows.label,
  option_rows.subtitle,
  option_rows.option_order
from winner_market
cross join (
  values
    ('Team World', 'All-Star Game team', 1),
    ('Team USA Stars', 'All-Star Game team', 2),
    ('Team USA Stripes', 'All-Star Game team', 3)
) as option_rows(label, subtitle, option_order)
on conflict (market_id, label) do update
set subtitle = excluded.subtitle,
    option_order = excluded.option_order,
    updated_at = now();

with mvp_market as (
  select id from public.all_star_markets where slug = '2026-asg-mvp'
)
insert into public.all_star_market_options (market_id, label, subtitle, option_order)
select
  mvp_market.id,
  option_rows.label,
  option_rows.subtitle,
  option_rows.option_order
from mvp_market
cross join (
  values
    ('Nikola Jokic', 'Team World', 1),
    ('Luka Doncic', 'Team World', 2),
    ('Victor Wembanyama', 'Team World', 3),
    ('Donovan Mitchell', 'Team World', 4),
    ('Karl-Anthony Towns', 'Team World', 5),
    ('Alperen Sengun', 'Team World', 6),
    ('Trae Young', 'Team World', 7),
    ('Domantas Sabonis', 'Team World', 8),
    ('Pascal Siakam', 'Team World', 9),
    ('Zach LaVine', 'Team World', 10),
    ('Kristaps Porzingis', 'Team World', 11),
    ('Jalen Brunson', 'Team USA Stars', 12),
    ('Anthony Edwards', 'Team USA Stars', 13),
    ('Kevin Durant', 'Team USA Stars', 14),
    ('LeBron James', 'Team USA Stars', 15),
    ('Jayson Tatum', 'Team USA Stars', 16),
    ('Tyrese Haliburton', 'Team USA Stars', 17),
    ('Anthony Davis', 'Team USA Stars', 18),
    ('Evan Mobley', 'Team USA Stars', 19),
    ('James Harden', 'Team USA Stars', 20),
    ('Jaren Jackson Jr.', 'Team USA Stars', 21),
    ('Cade Cunningham', 'Team USA Stars', 22),
    ('Norman Powell', 'Team USA Stars', 23),
    ('Devin Booker', 'Team USA Stars', 24),
    ('Kyrie Irving', 'Team USA Stripes', 25),
    ('Kawhi Leonard', 'Team USA Stripes', 26),
    ('Jalen Williams', 'Team USA Stripes', 27),
    ('Jaylen Brown', 'Team USA Stripes', 28),
    ('Tyler Herro', 'Team USA Stripes', 29),
    ('Tyrese Maxey', 'Team USA Stripes', 30),
    ('Damian Lillard', 'Team USA Stripes', 31),
    ('Jarrett Allen', 'Team USA Stripes', 32),
    ('Jalen Johnson', 'Team USA Stripes', 33),
    ('Austin Reaves', 'Team USA Stripes', 34),
    ('James Wiseman', 'Team USA Stripes', 35),
    ('Coby White', 'Team USA Stripes', 36)
) as option_rows(label, subtitle, option_order)
on conflict (market_id, label) do update
set subtitle = excluded.subtitle,
    option_order = excluded.option_order,
    updated_at = now();

-- Manual resolve flow (run once each market is final):
-- 1) update public.all_star_markets set status = 'resolved', winning_option_id = <option_id> where slug = '<market_slug>';
-- 2) update public.all_star_picks p
--      set correct = (p.option_id = m.winning_option_id)
--    from public.all_star_markets m
--    where p.market_id = m.id
--      and m.slug = '<market_slug>';
